ecom_project1/nk_mart/core/urls.py
from django.urls import path
from core.views import index

urlpatterns = [
    
]

ecom_project1/nk_mart/nk_mart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as v


urlpatterns = [
    # path for error
    path("404", v.error404, name = "404"),
    
    # path for account (not built-in)
    # path("account/my_account", v.my_account, name = "my_account"),  # not required any more
    path("account/register", v.register, name = "handel_register"), #name = register is changed to handel_register because handel_register is the default name for register, if we are using django built-in for user account  
    path("account/login", v.Login, name = "handel_login"), #name = login is changed to handel_login because handel_login is the default name for login, if we are using django built-in for user account  
    
    # path for forget password which has default login, logout and others (i.e; instead of path("account/my_account", v.my_account, name = "my_account") path we can use the below path(django built-in))
    path('accounts/', include('django.contrib.auth.urls')),

    # path for profile
    path("account/profile", v.profile, name = "profile"),
    path("account/profile/update", v.profile_update, name = "profile_update"),
    path("about", v.about, name = "about"),
    path("contact", v.contact, name = "contact"),
    path('admin/', admin.site.urls),
    path("base/", v.base, name = "base"),
    path("", v.home, name = "home"),
    
    path("product", v.product, name = "product"),
    # path("review/", v.review, name = "review"),
    
    path('product/filter-data',v.filter_data,name="filter-data"), # for ajax
    
    path("product/<slug:slug>", v.Product_detail, name="product_detail"), # here name = product_detail should be same as in getabsolute_url method in models.py
    
    # cart related path
    path('cart/add/<int:id>/', v.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', v.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', v.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', v.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', v.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',v.cart_detail,name='cart_detail'),
    
    # path for checkout
    path("checkout", v.CHECKOUT, name= "checkout"),
    
    #path for place order
    path('checkout/placeorder',v.placeorder,name='placeorder'),
    
    path("success/", v.success, name = "success"),
    path("not_success/", v.not_success, name = "not_success"),
    
    path("your_order/", v.your_order, name = "your_order"),
    
    path("search", v.search, name = "search"),
    
    path("faqs/", v.faqs, name = "faqs"),
     
    path("wishlist/", v.WishlistView.as_view(), name = "wishlist"),
    path("add_wishlist/", v.add_wishlist, name = "add_wishlist"),
    path("delete_wishlist/", v.delete_wishlist, name = "delete_wishlist"),
    
    path("review/<int:id>", v.review, name = "review"),

    
     
] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_project1/nk_mart/core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
import datetime
from django.db.models import *

# Create your models here.
class Slider(models.Model):
    DISCOUNT_DEAL = (("HOT DEALS", "HOT DEALS"), ("NEW ARRIVALS", "NEW ARRIVALS"))
    Image = models.ImageField(upload_to = "media/slider_imgs")
    Discount_deal = models.CharField(choices = DISCOUNT_DEAL , max_length=100)
    Sale = models.IntegerField()
    Brand_name = models.CharField(max_length=200)
    Discount = models.IntegerField()
    Link = models.CharField( max_length=200)
    
    def __str__(self):
        return self.Brand_name
    
class Banner_area(models.Model):
    Image = models.ImageField(upload_to = "media/banner_imgs")
    Discount_deal = models.CharField( max_length=100)
    Quote = models.CharField(max_length=200)
    Discount = models.IntegerField()
    Link = models.CharField( max_length=200, null = True)
    
    def __str__(self):
        return self.Quote
    
class Main_category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Category(models.Model):
    main_category = models.ForeignKey(Main_category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name + " -- " + self.main_category.name

class Sub_category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.category.main_category.name + " -- " + self.category.name + " -- " +  self.name  
      
class Section(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Color(models.Model):
    code = models.CharField( max_length=100)
    
    def __str__(self):
        return self.code

class Brand(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    total_quantity = models.IntegerField()
    availability = models.IntegerField()
    featured_image = models.CharField(max_length=500)
    product_name = models.CharField(max_length=500)
    
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null = True)
    
    price = models.IntegerField()
    Discount = models.IntegerField()
    
    tax = models.IntegerField(null = True) 
    packing_cost = models.IntegerField(null = True)
    
    Product_information = RichTextField()
    model_name = models.CharField(max_length=200)
    Categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null = True)
    
    Tags = models.CharField( max_length=200)
    Description = RichTextField()
    section = models.ForeignKey(Section, on_delete=models.DO_NOTHING, null=True,blank=True)
    
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    
    def __str__(self):
        return self.product_name
   
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("product_detail", kwargs={'slug': self.slug})
    
   
    class Meta:
        db_table = "app_Product"

def create_slug(instance, new_slug=None):
    slug = slugify(instance.product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Product)


class Coupon_code(models.Model):
    code = models.CharField( max_length=100) 
    discount = models.IntegerField()
    
    def __str__(self):
        return self.code
       
    
class Product_image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE) 
    image_url = models.CharField(max_length=500)
    
class Additional_info(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE) 
    specification = models.CharField( max_length=300)
    detail = models.CharField( max_length=300)     
  
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField( max_length=200)
    lastname = models.CharField( max_length=200)
    country = models.CharField( max_length=200)
    address = models.TextField()
    city = models.CharField( max_length=200)
    state = models.CharField( max_length=200)
    postalcode = models.IntegerField()
    phone = models.IntegerField()
    email = models.EmailField( max_length=200)
    additional_info = models.TextField(blank = True)
    amount = models.CharField(max_length=100)
    payment_id = models.CharField( max_length=500, null = True, blank = True)
    paid = models.BooleanField(default = False, null = True)
    date = models.DateTimeField(default=datetime.datetime.now)
    

    def __str__(self):
        return self.user.username


   
class Order_item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=200)
    image = models.CharField(max_length=500)
    quantity = models.CharField( max_length=100)
    price = models.CharField( max_length=100)
    total = models.CharField( max_length=100)
    
    def __str__(self):
        return self.order.user.username
    
    
    
class Contact_us(models.Model):
    name = models.CharField( max_length=200)
    email = models.EmailField( max_length=200)
    subject = models.CharField( max_length=300)
    message = models.TextField()
    date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.email
    
    
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
     
    def __str__(self):
        return self.user.username


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField(max_length = 500)
    rate = models.IntegerField(default = 0, null = True)
    created_at = models.DateTimeField(default=datetime.datetime.now)

     
    def __str__(self):
        return self.user.username
    
    

ecom_project1/nk_mart/templates/includes/footer.html
<!-- footer-start -->
{% load static %}
<footer>
    <div class="fotter-area d-dark-bg">
        <div class="footer__top pt-80 pb-15">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-4 order-last-md">
                        <div class="row">
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Customer Care</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'faqs' %}">New Customers</a></li>
                                                <li><a href="{% url 'faqs' %}">How to use Account</a></li>
                                                <li><a href="{% url 'faqs' %}">Placing an Order</a></li>
                                                <li><a href="{% url 'faqs' %}">Payment Methods</a></li>
                                                <li><a href="{% url 'faqs' %}">Delivery &amp; Dispatch</a></li>
                                                <li><a href="{% url 'faqs' %}">Problems with Order</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Customer Service</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'contact' %}">Help Center</a></li>
                                                <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                                <li><a href="{% url 'contact' %}">Report Abuse</a></li>
                                                <li><a href="{% url 'contact' %}">Submit a Dispute</a></li>
                                                <li><a href="{% url 'contact' %}">Policies &amp; Rules</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-8 order-first-md">
                        <div class="footer__top-left">
                            <div class="row">
                                
                                <div class="col-xl-7 col-lg-6 col-md-6 col-sm-6">
                                    <div class="row">
                                        
                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                            <div class="footer__widget">
                                                <div class="footer__widget-title">
                                                    <h4>My Account</h4>
                                                </div>
                                                <div class="footer__widget-content">
                                                    <div class="footer__link">
                                                        <ul>
                                                            <li><a href="{% url 'faqs' %}">Product Support</a></li>
                                                            <li><a href="{% url 'cart_detail' %}">Checkout</a></li>
                                                            <li><a href="{% url 'cart_detail' %}">Shopping Cart</a></li>
                                                            <li><a href="{% url 'cart_detail' %}">Wishlist</a></li>
                                                            <li><a href="{% url 'contact' %}">Terms &amp; Conditions &amp;</a></li>
                                                            <li><a href="{% url 'faqs' %}">Redeem Voucher</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Quick Links</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'product' %}">Store Location</a></li>
                                                <li><a href="{% url 'profile' %}">My account</a></li>
                                                <li><a href="{% url 'your_order' %}">Order Tracking</a></li>
                                                <li><a href="{% url 'faqs' %}">FAQs</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div></div>
                                </div><div class="col-xl-5 col-lg-6 col-md-6 col-sm-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title mb-20">
                                            <h4>About The Store</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <p class="footer-text mb-35">Our mission statement is to provide the absolute best customer experience available in the Electronic industry without exception.</p>
                                            <div class="footer__hotline d-flex align-items-center mb-10">
                                                <div class="icon mr-15">
                                                    <i class="fal fa-headset"></i>
                                                </div>
                                                <div class="text">
                                                    <h4>Got Question? Call us 24/7!</h4>
                                                    <span><a href="tel:100-123-456-7890">(+100) 123 456 7890</a></span>
                                                </div>
                                            </div>
                                            <div class="footer__info">
                                                <ul>
                                                    <li>
                                                        <span>Add:  <a target="_blank" href="https://goo.gl/maps/c82DDZ8ALvL878Bv8"> #89 B/11, Domlur, Bangalore, Karnataka, India</a></span>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__bottom">
            <div class="container">
                <div class="footer__bottom-content pt-55 pb-45">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="footer__links text-center mb-25">
                                <p>
                                    <a href="{% url 'faqs' %}">Online Shopping</a>
                                    <a href="{% url 'faqs' %}">Promotions</a>
                                    <a href="{% url 'faqs' %}">My Orders</a>
                                    <a href="{% url 'faqs' %}">Help</a>
                                    <a href="{% url 'faqs' %}">Customer Service</a>
                                    <a href="{% url 'faqs' %}">Support</a>
                                    <a href="{% url 'faqs' %}">Most Populars</a>
                                    <a href="{% url 'faqs' %}">New Arrivals</a>
                                    <a href="{% url 'faqs' %}">Special Products </a>
                                    <a href="{% url 'faqs' %}">Manufacturers</a>
                                    <br>
                                    <a href="{% url 'faqs' %}">Garden Equipments</a>
                                    <a href="{% url 'faqs' %}">Powers And Hand Tools </a>
                                    <a href="{% url 'faqs' %}">Utensil &amp; Gadget </a>
                                    <a href="{% url 'faqs' %}">Printers</a>
                                    <a href="{% url 'faqs' %}">Projectors</a>
                                    <a href="{% url 'faqs' %}">Scanners</a>
                                    <a href="{% url 'faqs' %}">Store</a>
                                    <a href="{% url 'faqs' %}">Business</a>
                                </p>
                            </div>
                            <div class="payment-image text-center mb-25">
                                <a href="#"><img src="{% static 'assets/img/payment/payment.png' %}" alt=""></a>
                            </div>
                            <div class="copy-right-area text-center">
                                <p>Copyright © <span>NKMarket.</span> All Rights Reserved. Powered by <a href="#"><span class="main-color">NK-Groups.</span></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer-end -->

ecom_project1/nk_mart/templates/includes/header.html
{% load static %}
<!-- header-start -->
<header class="header d-blue-bg">
    <div class="header-top">
        <div class="container">
            <div class="header-inner">
                <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-7">
                        <div class="header-inner-start">
                            
                            
                            <div class="support d-none d-sm-block">
                                
                                {% if user.is_authenticated %}
                                <p>
                                    Welcome
                                    {% if user.first_name == "" %}
                                        {{user.email}}
                                    {% else %}
                                        {{user.first_name}} {{user.last_name}}    
                                    {% endif %}       
                                </p>
                                {% else %}
                                <p>Please do Login First...</p>
                                {% endif %}
                                    
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-5 d-none d-lg-block">
                        <div class="header-inner-end text-md-end">
                            <div class="ovic-menu-wrapper">
                                <ul>
                                    <li><a href="{% url 'about' %}">About Us</a></li>
                                    <li><a href="{% url 'your_order' %}">Order Tracking</a></li>
                                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                    <li><a href="{% url 'faqs' %}">FAQs</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-mid">
        <div class="container">
            <div class="heade-mid-inner">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                        <div class="header__info">
                            <div class="logo">
                                <a href="{% url 'home' %}" class="logo-image"><img src="{% static 'assets/img/logo/logo.svg' %}" alt="logo"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                        <div class="header__search" style = "margin-left : -100px;">
                            <form action="/search">
                                <div class="header__search-box" style = "width : 550px;" >
                                    <input class="search-input" type="text" placeholder="I'm shopping for..." name="query" id = "query">
                                    <button class="button" type="submit"><i class="far fa-search"></i></button>
                                </div>
                                <div class="header__search-cat" >
                                    <select>
                                        <option>All Categories</option>
                                        <option>Best Seller Products</option>
                                        <option>Top 10 Offers</option>
                                        <option>New Arrivals</option>
                                        <option>Phones &amp; Tablets</option>
                                        <option>Electronics &amp; Digital</option>
                                        <option>Fashion &amp; Clothings</option>
                                        <option>Jewelry &amp; Watches</option>
                                        <option>Health &amp; Beauty</option>
                                        <option>Sound &amp; Speakers</option>
                                        <option>TV &amp; Audio</option>
                                        <option>Computers</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>

                    {% include 'includes/modal.html' %}
                
                </div>
            </div>
        </div>
    </div>
    <div class="header__bottom">
        <div class="container">
            <div class="row g-0 align-items-center">
                <div class="col-lg-3">                        
                    <div class="cat__menu-wrapper side-border d-none d-lg-block">
                        <div class="cat-toggle">
                            <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i> Shop by department</button>
                            <div class="cat__menu">
                                <nav id="mobile-menu" style="display: block;">
                                    <ul>
                                        
                                        {% for i in main_category %}
                                              
                                        <li>
                                            <a href="{% url 'product' %}">{{i.name}} <i class="far fa-angle-down"></i></a>
                                            <ul class="mega-menu">

                                                
                                                {% for cat in i.category_set.all  %}
                                                {% comment %} here category is the model class name and should be in lower case {% endcomment %}

                                                <li><a href="{% url 'product' %}" style = "color : orange">{{cat.name}}</a>
                                                    <ul class="mega-item">

                                                        
                                                        {% for sub_cat in cat.sub_category_set.all %}
                                                            
                                                        <li><a href="{% url 'product' %}">{{sub_cat.name}}</a></li>

                                                        {% endfor %}
                                                            
                                                    </ul>
                                                </li>
                                                    
                                                {% endfor %}
                                                    
                                                
                                            </ul>
                                        </li>

                                        {% endfor %}
                                        
                                        {% comment %} <li><a href="shop.html">Health &amp; Beauty</a></li> {% endcomment %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-3">
                  <div class="header__bottom-left d-flex d-xl-block align-items-center">
                    <div class="side-menu d-lg-none mr-20">
                      <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                    </div>
                    <div class="main-menu d-none d-lg-block">
                        <nav>
                            <ul>
                                <li>
                                    <a href="{% url 'home' %}" class="active">Home</i></a>
                                    
                                </li>
                                <li><a href="{% url 'about' %}">About Us</a></li>

                                <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                <li><a href="{% url 'product' %}">Product</a></li>

                            
                                <li><a href="{% url 'your_order' %}">My Orders </i></a>
                                    
                                </li>
                                
                            </ul>
                        </nav>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-9">
                    <div class="shopeing-text text-sm-end">
                        <p>Spend &#x20B9;500 more and get free shipping!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- header-end -->

<!-- offcanvas area start -->
<div class="offcanvas__area">
    <div class="offcanvas__wrapper">
    <div class="offcanvas__close">
        <button class="offcanvas__close-btn" id="offcanvas__close-btn">
            <i class="fal fa-times"></i>
        </button>
    </div>
    <div class="offcanvas__content">
        <div class="offcanvas__logo mb-40">
            <a href="{% url 'home' %}">
            <img src="{% static 'assets/img/logo/logo.svg' %}" style= "width:100px; margin-left:50px" alt="logo">
            </a>
        </div>
        <div class="offcanvas__search mb-25">
            <form action="/search">
                <input type="text" placeholder="What are you searching for?"  name="query" id = "query">
                <button type="submit" ><i class="far fa-search"></i></button>
            </form>
        </div>
        <div class="mobile-menu fix"></div>
        <div class="offcanvas__action">

        </div>
    </div>
    </div>
</div>
<!-- offcanvas area end -->      
<div class="body-overlay"></div>
<!-- offcanvas area end -->